apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/html/1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/html/2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/html/3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"